import { InvitationConfig } from '../models/invitation.model';

// Replace only this file when personalizing the invitation.
export const invitationConfig: InvitationConfig = {
  couple: {
    groomName: 'Groom Name',
    brideName: 'Bride Name',
    coupleDisplayName: 'Groom Name & Bride Name',
    couplePhoto: 'assets/engagement/images/couple-main.webp',
    secondaryPhoto: 'assets/engagement/images/couple-secondary.webp',
  },
  event: {
    title: 'WE ARE GETTING ENGAGED',
    date: '20 December 2026',
    time: '6:30 PM onwards',
    venueName: 'Engagement Venue',
    venueAddress: 'City, India',
    googleMapsUrl: 'https://maps.google.com',
  },
  messages: {
    welcomeMessage: 'With joy in our hearts, we invite you to open this engagement invitation.',
    coupleMessage: 'Two hearts, one beautiful beginning.',
    invitationMessage:
      'With immense joy in our hearts,\nwe invite you to celebrate\nthe beginning of our forever.',
    countdownMessage: 'Counting down to our special day',
    eventStartedMessage: 'Our beautiful journey begins today.',
    closingMessage: 'Your presence will make\nour celebration even more special.',
    closingSupportingMessage: "We can't wait to celebrate with you ❤️",
  },
  labels: {
    coverFamilyLine: 'Together with our families',
    coverTitle: "You're Invited",
    coverSealFallback: 'G & B',
    openInvitation: 'Open Invitation',
    openingInvitation: 'Opening...',
    openInvitationAriaLabel: 'Open invitation',
    openingInvitationAriaLabel: 'Opening invitation',
    coupleEyebrow: 'Two hearts, one promise',
    viewInvitation: 'View Our Invitation',
    viewInvitationAriaLabel: 'View our invitation',
    date: 'Date',
    time: 'Time',
    venue: 'Venue',
    continue: 'Continue',
    countdownEyebrow: 'Countdown',
    countdownInvalidMessage: 'Countdown will appear once the event date and time are configured.',
    countdownAriaPrefix: 'Countdown to',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    venueEyebrow: 'Venue',
    venueHeading: 'Where the celebration unfolds',
    getDirections: 'Get Directions',
    getDirectionsAriaPrefix: 'Get directions to',
    getDirectionsAriaSuffix: 'in a new tab',
    addToCalendar: 'Add to Calendar',
    addToCalendarAriaPrefix: 'Add to calendar:',
    familyBlessingsAriaLabel: 'Family blessings',
    familyBlessingsIntro: 'With blessings from',
    familySeparator: 'and',
    closingEyebrow: 'Thank you',
    closingSignoff: 'With Love,',
    replayInvitation: 'Replay Invitation',
    replayInvitationAriaLabel: 'Replay invitation from the beginning',
    musicOn: 'Music On',
    musicOff: 'Music Off',
    muteMusicAriaLabel: 'Mute background music',
    playMusicAriaLabel: 'Play background music',
    invitationProgressAriaLabel: 'Invitation progress',
    storyRegionAriaLabel: 'Engagement invitation story',
    back: 'Back',
    backAriaLabel: 'Go back to the previous invitation screen',
    progressSeparator: 'of',
  },
  families: {
    groomFamily: 'Groom Family',
    brideFamily: 'Bride Family',
  },
  theme: {
    primaryColor: '#b76e79',
    secondaryColor: '#4b1f32',
    backgroundColor: '#fffaf3',
    accentColor: '#c8a45d',
  },
  music: {
    enabled: false,
    filePath: 'assets/engagement/music/background-music.mp3',
  },
  features: {
    showCountdown: true,
    showVenue: true,
    showFamilies: true,
    showMusic: false,
    showGallery: false,
    showCalendar: true,
  },
};
